- hashbang.sh
That's really all. Merging if no complaints.
> Fix typo in hashbang.sh.

- src/hashbang.sh
> known_hosts key automatic insertion

- src/hashbang.sh
> As requested. Fixed bail, rm $host_data

- src/hashbang.sh
This commit improves upon the POSIX compliance of the hashbang.sh script.
However, due to unfortunate circumstances, I have been unable to test the account creation itself, as the server would return HTTP/1.1 400. Regardless of this, the conformance should now be vastly improved, and has been tested with bash and dash.
The reason for this pull request is to allow more than one set of eyes to review the code before it is finally merged.
> Improve POSIX compliance.

- src/hashbang.sh
Print out what the error was. Could be useful if it's just the account name is taken or something.
> PR for printing out errors

- src/hashbang.sh
Fairly trivial change, but this may help not to run into the same issue again.
> src/hashbang.sh: Comment on keeping the regexp synced

- src/hashbang.sh
> hashbang.sh: Fix whitespace and comments

- server.py
Depends on https://github.com/hashbang/provisor/pull/21
Closes issue #58
> UserCreate: Handle UNKNOWN_HOST from provisor

- LICENSE.md
- server.py
Warning: This is not tested in place, please test/review before merging.
> added JSON endpoint to get port <-> subdomain mappings from LDAP server

- server.py
Please merge and redeploy ASAP, this breaks user registration.
> server.py: Import the exception class properly

- server.py
> pretty print JSON

- server.py
In the short term, this will be replaced by data help in the new [userdb](https://github.com/hashbang/hashbang/blob/master/userdb/).
However, providing hardcoded data will facilitate @Aagat's development of [`new.hashbang.sh`](https://github.com/hashbang/new.hashbang.sh).
> Provide servers' GPS coordinates

- server.py
Better late than never, even though this is going to die soon.
> Make PEP8-clean

- server.py
> server: Fixup CSP

- src/hashbang.sh
- static/index.html
> Properly break after a successful key creation

- src/hashbang.html
- static/index.html
Also explains in the comments why piping the output from GnuPG is dangerous.
> hashbang.html: More direct one-liner

- src/hashbang.html
- src/local.css
- static/index.html
Made the text Bold in (hopefully) all browsers since it was normal in Firefox.
> Making "#!" bold in hashbang.html

- server.py
> TLS: Use curve P256

- src/hashbang.sh
- static/index.html
Thanks to @anowlcalledjosh for noticing the issue and sending a patch.
> Fix server statistics

- src/hashbang.sh
- static/index.html
This ought to fix the CI failures, and I took the opportunity to refactor slightly.
> Resolve shellcheck warning SC2183

- src/hashbang.html
- src/local.css
- static/index.html
Currently, the website uses a static width and absolute position hackery. This instead uses flexbox and should perfectly align text on the page without cutting it off.
Pinging @lrvick to review.
> src/{hashbang.html,local.css}: Fix alignment of static page content

- Dockerfile
- Pipfile
- Pipfile.lock
- requirements.txt
- reserved.py
- server.py
To keep the API the same, I've pulled out provisor and moved all calls
to userdb. Upgraded us to python3 and setup a Pipfile for local
development
> Upgrade to python3, swap ldap for userdb
